# Generated by Django 5.2.3 on 2025-06-13 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0003_securityquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('learning', 'Learning'), ('mastered', 'Mastered')], default='new', max_length=10),
        ),
        migrations.AddField(
            model_name='studysession',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studysession',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
