# Generated by Django 5.2.3 on 2025-06-13 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0004_card_status_studysession_duration_studysession_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='options',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'Multiple Choice'), ('tf', 'True/False'), ('sa', 'Short Answer')], default='sa', max_length=10),
        ),
    ]
