# Generated by Django 5.2.3 on 2025-06-20 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0005_card_options_card_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='studysession',
            name='avg_time_per_card',
            field=models.FloatField(default=0),
        ),
    ]
